apiVersion: v1
kind: Service
metadata:
  name: app-jwt-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-jwt-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-jwt-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: app-jwt-api
  template:
    metadata:
      labels:
        app: app-jwt-api
    spec:
      containers:
        - name: app-jwt-api
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
